# @package _global_
#change patch (line 5-15, choose one the three options), trainer vs tester (base_test line 88-89) and ckpt_path (line 93, comment it if you use training phase) and test period (2018 on OSE for DWS)
#change #training epochs, period of train/val/test

#changes in Bigger Model:  n_step=15 (instead of 10), dim_hidden=34 (instead of 32) in prior cost, dim_hidden=96 (instead of 48) in gradmod, bilin_quad: False (instead of True), and downsamp: 2 (instead of None)
#reduce time windows to 10


#reducing learning rate, changing time period of training/validation (test OSSE are the same with validation), apply real gap map for this OSSE training,
#save best weight every 50 epochs (I hope it works but not sure)
#reduce batch_size=4 here, since smaller data need smaller batchsize, to avoid overfit too early
#test period (2018 on OSE for DWS)  while 2017 for OSSE data
#change the number of epochs, 150 is enough, and save every 10 epochs

#IMPORTANT!!!! : data module is data.py for training/finetuning on OSE and data_DWS_OSSE_realgapMask_and_50percentArtificialPatches for OSSE

###NOTE on Nov 13th 2025:
# -For Flow Matching purpose, we change the test period to 2020 for OSE training, also train and validation
# - We use the square patches here as Flow Matching setting
# - We use the same UNet 3D transformer model as Flow Matching

paths:
    # # #for training OSSE
    # GT: /DATASET/data_nga/Delft3Dmodel_CMEMS_size200T300/Deflt3D/GT_Delft3D_size200T300_log10.nc
    # patch: /DATASET/data_nga/Delft3Dmodel_CMEMS_size200T300/Deflt3D/Obs_patch_Delft3D_size200T300_log10_0.5RemovedCloud_correctVersion.nc
    # path_real_data: /DATASET/data_nga/Delft3Dmodel_CMEMS_size200T300/CMEMS/GT_CMEMS_size200T300_log10.nc #6 years data from 2015 to 2020

    # #for training OSE, change test period to 2018
    GT: /Odyssey/private/n23nguye/data_nga/Delft3Dmodel_CMEMS_size200T300/CMEMS/GT_CMEMS_size200T300_log10.nc
    patch: /Odyssey/private/n23nguye/data_nga/Delft3Dmodel_CMEMS_size200T300/CMEMS/Obs_patch_CMEMS_size200T300_log10_0.5RemovedCloud_correctVersion.nc
    # path_real_data: /Odyssey/private/n23nguye/data_nga/Delft3Dmodel_CMEMS_size200T300/CMEMS/GT_CMEMS_size200T300_log10.nc #6 years data from 2015 to 2020


trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: 'data_instead_of_dataSCHISM_AugMoreRemovedPatches'
    # version: ''
  max_epochs: 100
  callbacks:
    - _target_: src.versioning_cb.VersioningCallback
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      every_n_epochs: 10
      filename: '{val_mse:.4f}-{epoch:03d}'

datamodule:
  _target_: src.data.BaseDataModule
  input_da: 
    _target_: src.utils.load_bbp_data
    path1: ${paths.GT}
    path2: ${paths.patch}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2015-01-01', '2019-08-31']}
    val: 
      time: {_target_: builtins.slice, _args_: ['2019-09-01', '2019-12-31']}
    test: 
      time: {_target_: builtins.slice,  _args_: ['2020-01-01', '2020-12-31']}
  xrds_kw:
    patch_dims: { time: 10, lat: 200, lon: 300}
    strides: { time: 1, lat: 200, lon: 300}
  dl_kw: {batch_size: 4, num_workers: 4}
  aug_factor: 1
  aug_only: True

model: #change models_Unet, cosanneal_lr_adam_Unet where fewer lr, unet and its parameters
  _target_: src.models_Unet3D_transformer.Lit4dVarNet
  opt_fn:
    _target_: src.utils.cosanneal_lr_adam_Unet
    _partial_: true
    lr: 0.0003 # Updated from 1e-3 to 0.0003 (1e-4 * 3)
    T_max: 175
  rec_weight:
      _target_: src.utils.get_triang_time_wei
      patch_dims: ${datamodule.xrds_kw.patch_dims}
      crop: {time: 0, lat: 0, lon: 0}
      offset: 1
  unet: 
    _target_: src.models_Unet3D_transformer.UNet3D_transformer_FlowMatching
    n_in_channels: 1
    # ${datamodule.xrds_kw.patch_dims.time}


entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
  # - _target_: src.test.base_test
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
    # ckpt_path: "/homes/n23nguye/4dvarnet-starter/outputs/2024-10-23/09-44-32/base_DWS200T300_AugPatches_BiggerModel_Conv2D_pretrainOSSE_realGapMap_newtimeperiod/checkpoints/val_mse=352.6970-epoch=199.ckpt"
