# @package _global_
#change patch (line 5-15, choose one the three options), trainer vs tester (base_test line 88-89) and ckpt_path (line 93, comment it if you use training phase)
#change #training epochs, period of train/val/test


#remember to change the save_top_k to 2 instead of 1 once you pretrained with another weight, so that it will save you at least another model

#changes in Bigger Model:  n_step=15 (instead of 10), dim_hidden=34 (instead of 32) in prior cost, dim_hidden=96 (instead of 48) in gradmod, bilin_quad: False (instead of True), and downsamp: 2 (instead of None)

#please change the time windows=10*number of samples/day
paths:
    # OSSE
    GT: /DATASET/data_nga/SCHISM_hourly/OSSE/SCHISM_hourly_cropped_log10.nc
    patch: /DATASET/data_nga/SCHISM_hourly/OSSE/Obs_patch_SCHISM_hourly_0.084percentageCloud.nc

    # #testing with OSE, change period of test
    # GT: data/Obs_SPM_log10_aNam.nc
    # patch: data/Obs_SPM_log10_aNam_removed_50percent_patch_again.nc


trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: 'AugRemovedMorePatches_BiggerModels_pretrained200eps'
  max_epochs: 250
  callbacks:
    - _target_: src.versioning_cb.VersioningCallback
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      save_top_k: 1
      filename: '{val_mse:.4f}-{epoch:03d}'

datamodule:
  _target_: src.data_SCHISM_AugMoreRemovedPatches_3slotsperday.BaseDataModule
  input_da: 
    _target_: src.utils.load_bbp_data
    path1: ${paths.GT}
    path2: ${paths.patch}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2020-01-02', '2020-09-30']}
    val: 
      time: {_target_: builtins.slice, _args_: ['2020-10-01', '2020-11-26']}
    test: 
      time: {_target_: builtins.slice,  _args_: ['2020-10-01', '2020-11-26']}
  xrds_kw:
    patch_dims: { time: 30, lat: 240, lon: 300}
    strides: { time: 1, lat: 240, lon: 300}
  dl_kw: {batch_size: 10, num_workers: 1}
  aug_factor: 1
  aug_only: True

model:
  _target_: src.models.Lit4dVarNet
  opt_fn:
    _target_: src.utils.cosanneal_lr_adam
    _partial_: true
    lr: 1e-3
    T_max: 175
  rec_weight:
      _target_: src.utils.get_triang_time_wei
      patch_dims: ${datamodule.xrds_kw.patch_dims}
      crop: {time: 0, lat: 0, lon: 0}
      offset: 1
  solver: 
    _target_: src.models.GradSolver
    n_step: 15
    lr_grad: 0.2
    prior_cost: 
      _target_: src.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 64
      downsamp: 2
      bilin_quad: False

    obs_cost: 
      _target_: src.models.BaseObsCost
    grad_mod: 
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 96


entrypoints:
  - _target_: pytorch_lightning.seed_everything
    seed: 333
  - _target_: src.train.base_training
  # - _target_: src.test.base_test
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
    # ckpt_path: "/homes/n23nguye/4dvarnet-starter/outputs/2024-03-06/11-51-56/base_SCHISM_AugPatches_BiggerModel/AugRemovedMorePatches_BiggerModels/checkpoints/val_mse=27.5895-epoch=196.ckpt"
